### PR TITLE
Create the interface for live transcription

### PR DESCRIPTION
**Pull request by yottalogical**
Tasks:
- [x] Data send/receive interface
- [x] Options
- [x] Response
- [ ] Documentation
- [x] Examples
- [x] Remove `old_live`
- [x] Bump version

### CODE REVIEW

**Comment by yottalogical** [comment]
It seems like GitHub CI isn't using Rust 1.63.0 yet, and therefore doesn't know about the latest and greatest from Clippy.

**Comment by yottalogical** [comment]
Just need to finish up the docs now!

**Comment by JohnTheCoolingFan** [comment]
Is this PR still being developed? The new features look really nice.

**Comment by andrewhalle** [comment]
We plan to merge this, but have no timeline for doing so right now. I hope to get to it soon.

**Comment by TheAce4K** [comment]
Any update on this? Is there any assistance needed to get this merged?

**Comment by DamienDeepgram** [comment]
This has been addressed in this PR: https://github.com/deepgram-devs/deepgram-rust-sdk/pull/76

**Comment by yottalogical** [comment]
🫡

**Pull request closed without merging**
